services:
  server:
    build:
      context: .
    container_name: file_content_scraper
    working_dir: /app
    restart: on-failure
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
